pipeline {
    agent any
environment {
    someVar="${env.envTest}"
    someVar2="${env.envTest2}"
    someVa3r="${env.envTest3}"
}
    stages {
        stage('stage one') {
            steps {
                echo someVar
            }
        }
        stage('stage two') {
            steps {
                echo someVar2
                echo someVar3
            }
        }
    }
}
