pipeline {
    agent any
    
environment {
    someVar="${env.envTest}"
    someVar2 = "${env.envTest2}"
    someVar3="${env.envTest3}"
}
    stages {
        stage('stage one') {
            steps {
                      configFileProvider(
        [configFile(fileId: 'ab3f322a-2589-4d3d-b849-6b8052a11247',variable:'envTest')]) {
         echo envTest
          echo "${env.envTest}"
    }
                echo someVar
            }
        }
        stage('stage two') {
            steps {
                echo someVar2
                echo someVar3
            }
        }
    }
}
